name: discord_bot_server
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.2 <3.0.0'


dependencies: 
  dart_appwrite: ^4.0.2
  logger: ^1.1.0
  nyxx: ^3.4.2
  uuid: ^3.0.6

dev_dependencies:
  lints: ^1.0.0
